name: "Delete linux VM"
description: "gcloud instance"
inputs:
  instance_name:
    description: "Instance to target"
    required: true
  gcp_credentials:
    description: "Credentials for GCP"
    required: true
  github_runner_token:
    description: "Personnal Access Token to register Runner"
    required: true
runs:
  using: "composite"
  steps:
    - name: 'Google Auth'
      id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ inputs.gcp_credentials }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v3'
      with:
        version: '>= 363.0.0'

    - name: 'Delete instance'
      run: >
        (yes | gcloud compute instances delete ${{ inputs.instance_name }} --delete-disks=all --zone=europe-west1-b) || true
      shell: bash

    - name: 'Delete runner'
      run: >
        curl -v --request DELETE
        --url  https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runners/${{ inputs.instance_name}}
        --header 'Authorization: Bearer ${{ inputs.github_runner_token }}'
        --header 'Accept: application/vnd.github+json'
        --fail
      shell: bash
